# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86960c4b282d68cd9560a4d51c82f07de6bc82201b5ebe4a8a660876905b1392829679aee57b6648dc53f6ab85fa60c3cf5b0380e512b275bacf21e88e6af14b

test:
  secret_key_base: 520f0fae9012947792c44d02571b51df2acc926fdb93fd4b35d94f8ea5b9fbe9b101e13160a20c9d021c2de0b5ecb598032646281ff9eef81f8b9190c5933342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
